<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\StereoKitEditor.Adapter.Abstractions\StereoKitEditor.Adapter.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\StereoKitEditor.Assets\StereoKitEditor.Assets.csproj" />
    <ProjectReference Include="..\..\src\StereoKitEditor.App\StereoKitEditor.App.csproj" />
    <ProjectReference Include="..\..\src\StereoKitEditor.Core\StereoKitEditor.Core.csproj" />
    <ProjectReference Include="..\..\src\StereoKitEditor.ProjectSystem\StereoKitEditor.ProjectSystem.csproj" />
    <ProjectReference Include="..\..\src\StereoKitEditor.Protocol\StereoKitEditor.Protocol.csproj" />
    <ProjectReference Include="..\..\src\StereoKitEditor.Runtime\StereoKitEditor.Runtime.csproj" />
    <ProjectReference Include="..\..\src\StereoKitEditor.Scene\StereoKitEditor.Scene.csproj" />
  </ItemGroup>

</Project>
